name: Integracion Continua - Ferreteria Frontend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Copiar el código del repositorio
    - name: Copiar codigo del repositorio
      uses: actions/checkout@v4

    # 2. Configurar Node.js (necesario para React / Vite / Vue)
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    # 3. Instalar las dependencias de tu ferretería (como React o Vite)
    - name: Instalar dependencias
      run: npm install

    # 4. Compilar el proyecto de la ferretería para producción
    - name: Compilar Frontend (Build)
      run: npm run build
